### ISSUE TITLE
[Bug]: MMRM in the Efficacy App

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/tern.mmrm#86] opened 2022-07-06 10:03 UTC
### What happened?

A bug happened!

Run the `teal.gallery::launch_app("efficacy")` and try to evaluate the MMRM module with the default arguments

### Relevant log output

```R
The following errors(s) occurred:
length of 'dimnames' [1] not equal to array extent

when evaluating the following code:
fit <- tern.mmrm::fit_mmrm(vars = list(response = "AVAL", covariates = NULL, id = "USUBJID", arm = "ARM", visit = "AVISIT"), data = anl, conf_level = 0.95, cor_struct = "unstructured", weights_emmeans = "proportional", optimizer = "automatic", parallel = TRUE)
```

**Comment by danielinteractive** [comment] 2022-07-06 19:35
duplicate of https://github.com/insightsengineering/tern/issues/628, will be fixed in https://github.com/openpharma/mmrm/issues/59

**Closed by danielinteractive** 2022-07-06 19:35 UTC
Labels: bug
